spring.application.name=patientManagement

spring.datasource.url=jdbc:mysql://localhost:3306/patientManagement_db
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.show-sql=true
# 1. STOP Hibernate from trying to manage the schema now that it's created
spring.jpa.hibernate.ddl-auto=update


server.port=9091